apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: 102026388922.dkr.ecr.us-east-1.amazonaws.com/clo835/assignment2:app-v0.1
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: "mysql-service.mysql"  # The DNS name of the MySQL service
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    - name: DATABASE
      value: "employees"

